################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
[ar]
languageName = "Ar"
languageCode = "ar-sa"
contentDir = "content/arabic"
languagedirection = "rtl"
weight = 0
